### ISSUE TITLE
Muuri is not defined. Could someone help me with this error? I am using it with laravel. This is where the error marks me. I'd appreciate your help

### ISSUE THREAD

**Issue by silfrido-porta** [haltu/muuri#451]

**Comment by Mathias-Tortomano** [comment]
Hello! I think it is a problem of the bookstore, the same thing has happened to me. unfortunately I think there is nothing to do, just wait for them to solve it. regards!

**Comment by Mathias-Tortomano** [comment]
Hello! I think it's a Muuri's problem, the same thing happened to me. unfortunately I think there is nothing to do, just wait for them to solve it. Greetings!

**Comment by niklasramo** [comment]
Could you (@silfrido-porta or @Mathias-Tortomano) provide a reduced test case in e.g. [codepen](https://codepen.io/) which shows this error? It's hard to do fix it without a reproducible test case.

**Comment by Mathias-Tortomano** [comment]
@niklasramo of course, this is my problem:
I have used muuri in this code, but it throws an error in muuri.min.js, line 21

`const grid = new Muuri('.grid', {
	layout: {
		rounding: false
	}
});`

this is the error:

muuri.min.js:21 Uncaught Error: No valid child element found within item element.
    at new ae (muuri.min.js:21)
    at new de (muuri.min.js:21)
    at Ee.add (muuri.min.js:21)
    at new Ee (muuri.min.js:21)
    at js.js:1

I thought it was muuri error because it detects said error in its js, but I think I am the only one with this problem :(

anyone have any idea how i can fix this?

**Comment by niklasramo** [comment]
As the error says, it seems that your item does not have a (required) child element. Have you checked if that's the case?

**Comment by nyneplus** [comment]
I have an Laravel 8 issue too. 

I have in my app.js
`require('muuri');`

after building (npm run dev) other includes work, but Muuri is undefined (even right after the require statement. )
I have no idea why it is not available but i can't make a codepen due to the laravel setup.

**Comment by gotshadowbantempaccount** [comment]
possible issue with shadow dom in vuejs got same error same other library

**Comment by Dhruv221198** [comment]
```
`<div` class="drag-options" id="drag-options" style="display: none; position: fixed; overscroll-behavior:none;bottom: 20px; right: 20px;z-index: 99999;">
        <div class="drop-zone-delete" style="border-top-color:red" data-id="delete">Delete</div>
        <div class="drop-zone-days" data-id="@DateTime.Today.AddDays(2).ToString("dd-MM-yyyy")">In Two Days</div>
        <div class="drop-zone-monday" data-id="@nextMonday.ToString("dd-MM-yyyy")">Next Monday</div>
        <div class="drop-zone-month" data-id="@firstDayOfNextMonth.ToString("dd-MM-yyyy")">Next Month</div>
        <div class="drop-zone-done" style="border-top-color:green" data-id="complete">Done</div>
    </div> 
This is my HTML code which I am trying in muuri .
dropzones = new Muuri('.drag-options', {
    layout: 400,
    layoutEasing: 'ease',
    dragEnabled: false,
    dragSortInterval: 0,
    layoutOnResize: true,
    dragStartPredicate: {
        handle: '.drop-zone'
    },
    dragReleaseDuration: 400,
    dragReleaseEasing: 'ease'
}); 
```
In the JS I am trying to initialize it but it throws errormuuri.min.js:21 Uncaught Error: No valid child element found within item element.
    at new Ye (muuri.min.js:21:50580)
    at new He (muuri.min.js:21:59351)
    at ii.add (muuri.min.js:21:77000)
    at new ii (muuri.min.js:21:71961)
    at <anonymous>:256:13
    at b (jquery.min.js:2:866)
    at Function.globalEval (jquery.min.js:2:2905)
    at Object.dataFilter (jquery.min.js:2:80720)
    at jquery.min.js:2:79185
    at l (jquery.min.js:2:79587)

@niklasramo can you help me in this.

**Comment by nammotot** [comment]
Hey guys, I found the solution for this error.

Your HTML should be structured as the following. 

```html
<div class="grid">
  <div class="item">
    <div class="item-content">
      <!-- Your content here -->
    </div>
  </div>
  <!-- more items... -->
</div>
```

You should have the container-class `grid` (This can be any name.)  
Within the container element, you should have `class="item"`  **(This cannot be any name.)**
